#!/bin/bash
# Usage: %COMMAND%
# Summary: Restart VPN process
# Help: This restarts the VPN process.  Any connected clients will be disconnected.
#

. $_EASY_DOCKER_VPN_ROOT/vars.sh
. $_EASY_DOCKER_VPN_ROOT/funcs.sh

_ensure_vpn_data

_restart_vpn
