#!/bin/bash
# Usage: %COMMAND% user [easyrsa args]
# Summary: Issues a new certificate for user
# Help: When complete, there will be a file in the local directory called $user.conn.ovpn
#
# Examples:
#
#    # issue a certificate for sally with a password (will be prompted)
#    %COMMAND% sally
#
#    # issue a certificate for bob with no password on the key
#    %COMMAND% bob nopass
#

. $_EASY_DOCKER_VPN_ROOT/vars.sh
. $_EASY_DOCKER_VPN_ROOT/funcs.sh

_ensure_vpn_data

USER=$1

if [[ -z $USER ]]; then
	echo "Missing required argument user"
	exit 1
fi

set -e

VOLUME_ARG=$(_volume_arg)

docker run --rm -it $VOLUME_ARG $OVPN_IMAGE easyrsa build-client-full $*
docker run --rm -it $VOLUME_ARG $OVPN_IMAGE ovpn_getclient $USER > $USER.conn.ovpn

echo "Config for $USER saved to $USER.conn.ovpn"
